In [4]:
import numpy as np

In [24]:
array1 = np.array([1, 2, 3])
print("type: ", type(array1))
print("shape: ", array1.shape)
print("array: ", array1)
print("array[0]: ", array1[0])

type:  <class 'numpy.ndarray'>
shape:  (3,)
array:  [1 2 3]
array[0]:  1


In [23]:
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("type: ", type(array2))
print("shape: ", array2.shape)
print("array: \n", array2)
print("array[0]: \n", array2[0, 0])
print("slice: \n", array2[:2, 1:3])

type:  <class 'numpy.ndarray'>
shape:  (3, 4)
array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
array[0]: 
 1
slice: 
 [[2 3]
 [6 7]]


In [21]:
array_one = np.ones((3, 1))
array_zero = np.zeros((3, 1))
array_full = np.full((5, 2), 11)
array_eye = np.eye(3)
array_random = np.random.random((3, 2))
print("one\n", array_one)
print("zero\n", array_zero)
print("full\n", array_full)
print("eye\n", array_eye)
print("random\n", array_random)

one
 [[1.]
 [1.]
 [1.]]
zero
 [[0.]
 [0.]
 [0.]]
full
 [[11 11]
 [11 11]
 [11 11]
 [11 11]
 [11 11]]
eye
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random
 [[0.01273094 0.63425364]
 [0.33834878 0.63939473]
 [0.9442488  0.36678013]]


In [27]:
# slices will change the original
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array2_part = array2[0:2, 0:2]
array2_part[0, 0] = 888
print(array2_part)
print(array2)

[[888   2]
 [  5   6]]
[[888   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
# two types of slice, int and int:int
array2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array2_row1 = array2[0:1, 0:2]
array2_row2 = array2[0, 0:2]
print(array2_part1)
print(array2_part2)
print(array2_part1.shape)
print(array2_part2.shape)
print(type(array2_part1))
print(type(array2_part2))

array2_col2 = array2[0:2, 0]  # turned into a row
print(array2_col2)
print(array2_col2.shape)

[[1 2]]
[1 2]
(1, 2)
(2,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 5]
(2,)


In [31]:
# Integer array indexing

In [ ]:
# http://cs231n.github.io/python-numpy-tutorial/#numpy-arrays